Musics_Anime = {
    "https://www.youtube.com/watch?v=jBhM-b93bsY":["bleach"], #On The Precipice Of Defeat
    "https://www.youtube.com/watch?v=VGS9nrEwXmw":["naruto"], #Sadness & Sorrow
    "https://www.youtube.com/watch?v=pMTF1RCDmhg":["inazuma eleven"], #Générique Fr
    "https://www.youtube.com/watch?v=KdGOV8FX6F4":["death note"], #Opening 1
    "https://www.youtube.com/watch?v=5-Ltm-3lmss":["seven deadly sins", "nanatsu no taizai"], #Perfect Time
    "https://www.youtube.com/watch?v=OugVczuA55s":["jojo", "jojo's"], #Il vento d'oro
    "https://www.youtube.com/watch?v=kIwmrk7LoDk":["fairy tail"], #Main Theme
    "https://www.youtube.com/watch?v=qR6dzwQahOM":["death note"], #L Theme
    "https://www.youtube.com/watch?v=Ppl21c_zKo8":["ajin"], #Can you sleep at night
    "https://www.youtube.com/watch?v=XXjgwpayNoM":["bleach"], #Ranbu no melody
    "https://www.youtube.com/watch?v=1H6lPlQ7jr8":["demon slayer", "kimetsu no yaiba"], #Gurenge
    "https://www.youtube.com/watch?v=B7uMdmCQabc":["full metal alchemist brotherhood"], #Again
    "https://www.youtube.com/watch?v=XMeQeIG_rQg":["black clover"], #Black catcher
    "https://www.youtube.com/watch?v=tK-d2LJlaaQ":["hunter x hunter"], #Hunting for your dreams
    "https://www.youtube.com/watch?v=qPbA0mMGsSg":["fate"], #Brave shine
    "https://www.youtube.com/watch?v=ORe7gt-mY14":["full metal alchemist"], #Rewrite
    "https://www.youtube.com/watch?v=GwaRztMaoY0":["jujutsu kaisen"], #Kaikai Kitan
    "https://www.youtube.com/watch?v=A2cTn1DtwEQ":["haikyuu"], #I'm a Believer
    "https://www.youtube.com/watch?v=OzKLiHJGZbw":["shield hero", "tate no yuusha"], #Faith
    "https://www.youtube.com/watch?v=CUT4-fCRvs4":["rent a girlfriend"], #First Drop
    "https://www.youtube.com/watch?v=JBqxVX_LXvk":["fire force", "enen no shouboutai"], #Inferno
    "https://www.youtube.com/watch?v=NL8gVtGAQpE":["kaguya-sama : love is war", "kaguya-sama", "kaguya sama"], #Love dramatic
    "https://www.youtube.com/watch?v=xEVcTStgA4A":["vinland saga"], #Opening 1
    "https://www.youtube.com/watch?v=AwHapidVQlI":["re:zero", "re zero"], #Realize
    "https://www.youtube.com/watch?v=gWCnKoEgfP0":["noragami"], #Goya No Machiawase
    "https://www.youtube.com/watch?v=2gdLc0l7gkk":["kakegurui"], #Deal with the devil
    "https://www.youtube.com/watch?v=SohCAjC-Npk":["dr stone"], #Sangenshoku
    "https://www.youtube.com/watch?v=LKP-vZvjbh8":["attaque des titans", "l'attaque des titans", "shingeki no kyojin"], #Shinzou wo Sasageyo
    "https://www.youtube.com/watch?v=y-q3br6WcGc":["fairy tail"], #Snow Fairy
    "https://www.youtube.com/watch?v=CkgQIc5vqf4":["ao no exorcist", "blue exorcist"], #Core Pride
    "https://www.youtube.com/watch?v=uMeR2W19wT0":["tokyo ghoul"], #Unravel
    "https://www.youtube.com/watch?v=zzJ8U8OtEsE":["soul eater"], #Resonance
    "https://www.youtube.com/watch?v=eRJyYfAq2tk":["the god of highschool"], #Contradiction
    "https://www.youtube.com/watch?v=apII5VFTce0":["tower of god"], #Top
    "https://www.youtube.com/watch?v=rh-xfHTJp6M":["violet evergarden"], #Sincerely
    "https://www.youtube.com/watch?v=rEzs6Bd_jAw":["the promised neverland"], #Identity
    "https://www.youtube.com/watch?v=wm37xkws5lQ":["your lie in april"], #Hikaru Nara
    "https://www.youtube.com/watch?v=6CBp4qylX6I":["no game no life"], #This game
    "https://www.youtube.com/watch?v=kPSTGGDAFGI":["danmachi"], #Hey world
    "https://www.youtube.com/watch?v=Bw-5Lka7gPE":["mob psycho 100"], #99
    "https://www.youtube.com/watch?v=vV3l_1j8pPE":["food wars", "shokugeki no soma"], #Kibo no uta
    "https://www.youtube.com/watch?v=_DwbXmr70C0":["death parade"], #Flyers
    "https://www.youtube.com/watch?v=VtNgeDxYJzE":["my hero acadamia", "boku no hero academia"], #Polaris
    "https://www.youtube.com/watch?v=akM53Bs58Bw":["parasyte"], #Let me hear
    "https://www.youtube.com/watch?v=4DcR_BgyQ7k":["sword art online"], #Overfly
    "https://www.youtube.com/watch?v=6jrllECbLfA":["vinland saga"], #Dark Crow
    "https://www.youtube.com/watch?v=n4o-i71Jz4E":["your name"], #ZenZenZense
    "https://www.youtube.com/watch?v=hJgJTTIbMDI":["one piece"], #One day
    "https://www.youtube.com/watch?v=CFM_zypYFHM":["one piece"], #Op 10
    "https://www.youtube.com/watch?v=aJRu5ltxXjc":["naruto"] #Blue Bird
}

Musics_Rock = {
    "https://www.youtube.com/watch?v=K5_EBAzIPJM":["angie"],
    "https://www.youtube.com/watch?v=hTWKbfoikeg":["smells like teen spirit"],
    "https://www.youtube.com/watch?v=ndEQ1hnYj0Y":["going down south"],
    "https://www.youtube.com/watch?v=Zi_XLOBDo_Y":["billie jean"],
    "https://www.youtube.com/watch?v=GlPlfCy1urI":["your song"],
    "https://www.youtube.com/watch?v=l482T0yNkeo":["highway to hell"],
    "https://www.youtube.com/watch?v=_tHbSMQeCdk":["cendrillon"],
    "https://www.youtube.com/watch?v=YoDh_gHDvkk":["under pressure"],
    "https://www.youtube.com/watch?v=MbXWrmQW-OE":["message in a bottle"],
    "https://www.youtube.com/watch?v=34ZmKbe5oG4":["another brick in the wall"]
}
